name = "%worker_name%"
main = "_worker.js"
compatibility_date = "2025-02-06"

routes = [
  { pattern = "%worker_name%.%domain_name%", custom_domain = true },
  { pattern = "quiz.int.vidio.com.%worker_name%.%domain_name%", custom_domain = true }
]

workers_dev = false

[vars]
CHECK_API_BASE = "https://check.installer.us.kg"
